#!/bin/bash
read -r -d '' HEADER <<-'EOF'
:::::::. :::::::..  .,::::::   :::.     .        :
;;;'';;';;;;``;;;; ;;;;''''   ;;`;;    ;;,.    ;;;
 [[[__[[\.[[[,/[[['  [[cccc   ,[[ '[[,  [[[[, ,[[[[,
 $$""""Y$$$$$$$$c    $$""""  c$$$cc$$$c $$$$$$$$"$$$
_88o,,od8P888b "88bo,888oo,__ 888   888,888 Y88" 888o
""YUMMMP" MMMM   "W" """"YUMMMYMM   ""` MMM  M'  "MMM

       Bash   Rules   Everything   Around   Me
-----------------------------------------------------
EOF

# Bream setup script
# `setup local` - runs setup from working dir, like in a branch
# `setup files` - skips setup and just copies files from working dir
# `setup -b [branch]` - download and install a certain branch

bin_dir="$HOME"/.local/bin
config_dir="$HOME"/.config
cache_dir="$HOME"/.cache/bream
git_url=https://git.doordesk.net/adam/bream.git
git_branch="master"

if [ "$1" = -b ]; then
    git_branch="$2"
fi

if [ "$1" = local ]; then
    local_repo=0
fi

install_base_gentoo() {
    echo "Installing base..."

    sudo emerge -u \
        bat \
        btop \
        byobu \
        llvm-core/clang \
        coreutils \
        eselect-repository \
        fish \
        dev-vcs/git \
        gnome-keyring \
        kitty-terminfo \
        libsecret \
        man-db \
        man-pages \
        mosh \
        rsync \
        sl \
        app-arch/tar \
        app-text/tree \
        unrar \
        unzip \
        wget \
        &&

    # Neovim and deps
    sudo emerge -u \
        fzf \
        go \
        luarocks \
        neovim \
        nodejs \
        ripgrep \
        rubygems \
        tree-sitter-cli \
        &&

    # Yazi and deps
    sudo emerge -u \
        7zip \
        chafa\
        fd \
        ffmpeg \
        fzf \
        imagemagick \
        app-misc/jq \
        poppler \
        ripgrep \
        yazi \
        zoxide \
        &&

    return 0
}

init_browser() {
    echo "Setting default browser..."

    # Unset BROWSER because xdg gets pissy if it doesn't feel like it's the authority
    unset BROWSER &&
    xdg-settings set default-web-browser librewolf.desktop &&
    # Set it anyway
    export BROWSER=librewolf || return 1

    return 0
}

init_pywalfox() {
    if ! test -f "$HOME"/.librewolf/native-messaging-hosts/pywalfox.json; then
        echo "Configuring pywalfox..."
        pywalfox install --browser librewolf || return 1
    fi

    return 0
}

init_wallpaper() {
    # Copy default wallpaper if it doesn't exist
    if ! test -f "$HOME"/Pictures/Wallpapers/bream.jpg; then
        if ! test -d "$HOME"/Pictures/Wallpapers; then
            mkdir -p "$HOME"/Pictures/Wallpapers &&
            curl -so "$HOME"/Pictures/Wallpapers/bream.jpg https://old.doordesk.net/bream.jpg || return 1
        fi
    fi

    return 0
}

init_wal() {
    if ! [ -d "$HOME"/.cache/wal ]; then
        bream setbg
    else
        bream setbg -r
    fi || return 1

    return 0
}

install_gui_gentoo() {
    sudo eselect repository add librewolf git https://codeberg.org/librewolf/gentoo.git
    sudo emaint sync -r librewolf

    sudo emerge -u \
        acpi \
        gnome-themes-standard \
        librewolf-bin \
        noto \
        noto-cjk \
        noto-emoji \
        playerctl \
        wallust \
        zathura \
        &&

    # Mango setup
    sudo emerge -u \
        cliphist \
        dunst \
        mangowm \
        polkit \
        kitty \
        kitty-shell-integration \
        pipewire \
        awww \
        uwsm \
        wl-clip-persist \
        waybar \
        wireplumber \
        wofi \
        xdg-desktop-portal \
        xdg-desktop-portal-gtk \
        xdg-desktop-portal-wlr \
        &&

    # Set dark theme
    # Unset and then reset to ensure it sticks in case dconf doesn't exist
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light' &&
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark' &&
    gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita' &&
    gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark' &&

    return 0
}

install_extras_gentoo() {
    sudo emerge -u \
        discord \
        element-desktop-bin \
        gimp \
        inkscape \
        telegram-desktop-bin \
        thunderbird-bin \
        &&

    return 0
}

install_shell() {
    if ! [ "$SHELL" = "/usr/bin/fish" ]; then
        sudo chsh -s /usr/bin/fish "$USER" &&
        echo "Reboot for changes to take effect"
    fi

    return 0
}

install_config() {
    [ ! -d "$config_dir" ] && { mkdir -p "$config_dir" || return 1; }

    cd "$cache_dir"/config &&
    for file in *; do
        local oldfile="$config_dir"
        # TODO: Add clean install option
        # [ -e "$oldfile" ] && rm -rf "$oldfile"
        cp -r --update=all "$file" "$oldfile" || break
    done || return 1

    return 0
}

install_bin() {
    [ ! -d "$bin_dir" ] && { mkdir -p "$bin_dir" || return 1; }

    cd "$cache_dir" &&
    cp -r --update=all bin/* "$bin_dir" || return 1

    return 0
}

install_home() {
    cd "$cache_dir"/home &&

    for file in *; do
        if [ -d "$file" ]; then
            if [ -d "$HOME/.$file" ]; then
                cp -r "$file"/* "$HOME"/."$file"/ || break
            else
                cp -r "$file" "$HOME"/."$file" || break
            fi
        else
            cp "$file" "$HOME"/."$file" || break
        fi
    done || return 1

    return 0
}

cleanup() {
    [ -d "$cache_dir" ] && { rm -rf "$cache_dir" && return 0; } || return 0
}

install_portage() {
    yes | sudo cp -r portage/* /etc/portage/ || return 1

    return 0
}

setup_gentoo() {
    cleanup &&

    # Make sure .cache exists
    if ! [ -d "$HOME"/.cache ]; then
        mkdir "$HOME"/.cache
    fi &&

    # Sync files
    if [ "$local_repo" ]; then
        cp -r . "$cache_dir"
    else
        git clone --branch "$git_branch" "$git_url" "$cache_dir"
    fi &&

    install_bin &&
    install_home &&
    install_config &&
    install_portage &&


    if [ "$1" -ge 1 ]; then
        install_base_gentoo || return 1
    fi &&

    if [ "$1" -ge 2 ]; then
        install_gui_gentoo || return 1
        # init_browser &&
        # init_pywalfox &&
        # init_wallpaper &&
        # init_wal || return 1
    fi &&

    if [ "$1" -ge 3 ]; then
        install_extras_gentoo || return 1
    fi &&

    install_shell &&

    # this should be last
    cleanup || return 1

    return 0
}

get_user_input() {
    read -r -p 'Choose your adventure:

 1. Base shell/CLI stuff only
 2. Above plus basic GUI stuff
 3. Above plus extras (bloat)

    Enter number: ' input &&

    # Filter input
    if ! [[ "$input" =~ ^[0-9]+$ ]]; then
        echo "Error: Not a number"
        exit 1

    elif [ "$input" -lt 1 ] || [ "$input" -gt 4 ]; then
        echo "Error: Input out of range"
        exit 1
    else
        echo "$input"
    fi || exit 1

    return 0
}

draw_header() {
    clear && echo "$HEADER" || return 1

    return 0
}

main() {
    user_input=$(get_user_input)

    draw_header

    # Detect OS and act accordingly
    . /etc/os-release
    local os_name=$NAME

    printf "Setup for %s\n\n" "$os_name"
    setup_gentoo "$user_input" || return 1

    return 0
}

draw_header

# Just copy files and exit
if [ "$1" = files ]; then
    echo "Copying files..."
    [ ! -d "$cache_dir" ] && { mkdir -p "$cache_dir" || return 1; }

    cp -r . "$cache_dir" &&

    if install_home &&
    install_config &&
    install_bin &&
    install_portage &&
    cleanup; then
        echo "Done" &&
        exit 0
    else
        cleanup
        echo "Error"
        exit 1
    fi
fi

{
    main "$@" && exit 0
    } || {
    echo "Setup failed" &&
    cleanup &&
    exit 1
}
