# Import colors
source = ~/.cache/wal/colors-hyprland.conf

background       = 0xFF$background
base             = 0xFF$color0
text             = 0xFF$foreground
alternate_base   = 0xFF$color1
bright_text      = 0xFF$color2
accent           = 0xFF$color3
accent_secondary = 0xFF$color4
