animations=1
layer_animations=1
animation_type_open=zoom
animation_type_close=zoom
animation_fade_in=1
animation_fade_out=1

fadein_begin_opacity=0.5
fadeout_begin_opacity=0.5
animation_curve_opafadein=0.5,0.5,0.75,1.0
animation_curve_opafadeout=0.5,0.5,0.75,1.0

zoom_initial_ratio=0.4
zoom_end_ratio=0.8

animation_duration_move=479
animation_curve_move=0.23,1.0,0.32,1.0

animation_duration_open=410
animation_curve_open=0.23,1.0,0.32,1.0

animation_duration_close=149
animation_curve_close=0.23,1.0,0.32,1.0

animation_duration_tag=200
animation_curve_tag=0.23,1.0,0.32,1.0

animation_duration_focus=177
animation_curve_focus=0.23,1.0,0.32,1.0
