# reload config
bind=SUPER,BackSpace,reload_config

# system stuff
bind=SUPER,q,killclient
bind=SUPER,f,togglefullscreen
bind=SUPER+SHIFT,e,quit

# spawn stuff
bind=SUPER,w,spawn,librewolf-bin
bind=SUPER,Return,spawn,foot
bind=SUPER,c,spawn,element-desktop
bind=SUPER+SHIFT,c,spawn,telegram-desktop
bind=SUPER,d,spawn,discord
bind=SUPER,e,spawn,thunderbird-bin

# window stuff
bind=SUPER,h,focusdir,left
bind=SUPER,k,focusstack,prev
bind=SUPER,j,focusstack,next
bind=SUPER,l,focusdir,right
bind=SUPER,Tab,view,-1

bind=SUPER+SHIFT,h,tagmon,left,0
bind=SUPER+SHIFT,j,exchange_stack_client,next
bind=SUPER+SHIFT,k,exchange_stack_client,prev
bind=SUPER+SHIFT,l,tagmon,right,0

bind=SUPER+SHIFT,f,togglefloating

# tag stuff
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0
bind=SUPER,0,view,0,0

bind=SUPER+SHIFT,1,tagsilent,1,0
bind=SUPER+SHIFT,2,tagsilent,2,0
bind=SUPER+SHIFT,3,tagsilent,3,0
bind=SUPER+SHIFT,4,tagsilent,4,0
bind=SUPER+SHIFT,5,tagsilent,5,0
bind=SUPER+SHIFT,6,tagsilent,6,0
bind=SUPER+SHIFT,7,tagsilent,7,0
bind=SUPER+SHIFT,8,tagsilent,8,0
bind=SUPER+SHIFT,9,tagsilent,9,0

# media controls
bind=NONE,XF86AudioNext,spawn,playerctl next
bind=NONE,XF86AudioPrev,spawn,playerctl previous
bind=NONE,XF86AudioPlay,spawn,playerctl play-pause

bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%+
bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%-
bind=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SINK@ toggle
bind=SHIFT,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SOURCE@ toggle
bind=NONE,XF86AudioMicMute,spawn,wpctl set-mute @DEFAULT_SOURCE@ toggle
