# Help popup
bind=SUPER,F1,spawn_shell,uwsm-app -- foot nvim -R ~/.config/mango/bind.conf
bind=SUPER+SHIFT,Slash,spawn_shell,uwsm-app -- foot nvim -R ~/.config/mango/bind.conf

# Global
bind=SUPER+SHIFT,e,spawn_shell,uwsm stop
bind=SUPER+SHIFT,p,spawn_shell,uwsm-app -- /home/"$USER"/.local/bin/bream setbg

bind=SUPER,BackSpace,reload_config
bind=SUPER,Tab,view,-1
bind=SUPER,f,togglefullscreen
bind=SUPER,p,toggleglobal
bind=SUPER,q,killclient

# Spawning
bind=SUPER+SHIFT,c,spawn_shell,uwsm-app -- Telegram
bind=SUPER+SHIFT,g,spawn_shell,uwsm-app -- lutris
bind=SUPER+SHIFT,i,spawn_shell,uwsm-app -- inkscape
bind=SUPER+SHIFT,m,spawn_shell,uwsm-app -- lmms
bind=SUPER+SHIFT,w,spawn_shell,uwsm-app -- trivalent

bind=SUPER,Return,spawn_shell,uwsm-app -- foot
bind=SUPER,c,spawn_shell,uwsm-app -- element-desktop-nightly
bind=SUPER,d,spawn_shell,uwsm-app -- discord
bind=SUPER,e,spawn_shell,uwsm-app -- thunderbird
bind=SUPER,g,spawn_shell,uwsm-app -- steam
bind=SUPER,i,spawn_shell,uwsm-app -- gimp
bind=SUPER,m,spawn_shell,uwsm-app -- spotify
bind=SUPER,r,spawn_shell,uwsm-app -- wofi --show drun
bind=SUPER,v,spawn_shell,uwsm-app -- virt-manager
bind=SUPER,w,spawn_shell,uwsm-app -- librewolf

# Move focus
bind=SUPER,h,focusdir,left
bind=SUPER,k,focusstack,prev
bind=SUPER,j,focusstack,next
bind=SUPER,l,focusdir,right

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0
bind=SUPER,0,view,0,0

# Move window
bind=SUPER+SHIFT,h,tagmon,left,0
bind=SUPER+SHIFT,j,exchange_stack_client,next
bind=SUPER+SHIFT,k,exchange_stack_client,prev
bind=SUPER+SHIFT,l,tagmon,right,0

bind=SUPER+SHIFT,1,tagsilent,1,0
bind=SUPER+SHIFT,2,tagsilent,2,0
bind=SUPER+SHIFT,3,tagsilent,3,0
bind=SUPER+SHIFT,4,tagsilent,4,0
bind=SUPER+SHIFT,5,tagsilent,5,0
bind=SUPER+SHIFT,6,tagsilent,6,0
bind=SUPER+SHIFT,7,tagsilent,7,0
bind=SUPER+SHIFT,8,tagsilent,8,0
bind=SUPER+SHIFT,9,tagsilent,9,0

# Window state
bind=SUPER+SHIFT,f,togglefloating

mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

# Media controls
bind=NONE,XF86AudioNext,spawn_shell,uwsm-app -- playerctl next
bind=NONE,XF86AudioPlay,spawn_shell,uwsm-app -- playerctl play-pause
bind=NONE,XF86AudioPrev,spawn_shell,uwsm-app -- playerctl previous
bind=NONE,XF86AudioStop,spawn_shell,uwsm-app -- playerctl stop

bind=NONE,XF86AudioLowerVolume,spawn_shell,uwsm-app -- wpctl set-volume @DEFAULT_SINK@ 5%-
bind=NONE,XF86AudioMicMute,spawn_shell,uwsm-app -- wpctl set-mute @DEFAULT_SOURCE@ toggle
bind=NONE,XF86AudioMute,spawn_shell,uwsm-app -- wpctl set-mute @DEFAULT_SINK@ toggle
bind=NONE,XF86AudioRaiseVolume,spawn_shell,uwsm-app -- wpctl set-volume @DEFAULT_SINK@ 5%+

bind=SHIFT,XF86AudioMute,spawn_shell,uwsm-app -- wpctl set-mute @DEFAULT_SOURCE@ toggle
bind=SHIFT,XF86AudioLowerVolume,spawn_shell,uwsm-app -- wpctl set-volume @DEFAULT_SOURCE@ 5%-
bind=SHIFT,XF86AudioRaiseVolume,spawn_shell,uwsm-app -- wpctl set-volume @DEFAULT_SOURCE@ 5%+

# Screenshot
bind=NONE,Print,spawn_shell,uwsm-app -- $HOME/.config/mango/scripts/screenshot.sh fullscreen
bind=SHIFT,Print,spawn_shell,uwsm-app -- $HOME/.config/mango/scripts/screenshot.sh region

bind=CTRL,Print,spawn_shell,uwsm-app -- $HOME/.config/mango/scripts/screenshot.sh freeze
bind=CTRL+SHIFT,Print,spawn_shell,uwsm-app -- $HOME/.config/mango/scripts/screenshot.sh freeze-region

bind=SUPER,Print,spawn_shell,uwsm-app -- $HOME/.config/mango/scripts/screenshot.sh annotate
