exec-once=uwsm-app -- waybar
exec-once=uwsm-app -- wl-clip-persist --clipboard regular
exec-once=uwsm-app -- wl-paste --type image --watch cliphist store
exec-once=uwsm-app -- wl-paste --type text --watch cliphist store
exec-once=uwsm-app -- awww-daemon && awww img "$(cat ~/.cache/wal/wal)"

cursor_hide_timeout=5
idleinhibit_ignore_visible=1
xwayland_persistence=0

source=./animations.conf
source=./bind.conf
source=./input.conf
source=./monitors.conf
source=./rules.conf
source=./style.conf
