source=./input.conf
source=./bind.conf
source=./monitors.conf
source=./animations.conf
source=./rules.conf
# source=./style.conf

# global
cursor_hide_timeout=5
exchange_cross_monitor=1
focus_cross_monitor=1
focus_cross_tag=1
idleinhibit_ignore_visible=1
view_current_to_back=1
xwayland_persistence=0

# allow_tearing=2
# syncobj_enable=1

# shadows
layer_shadows=1
shadows=1
shadows_blur=30
shadows_size=15

# borders
border_radius=5
borderpx=2

# style
cursor_size=24
cursor_theme=Adwaita

# exec-once=/home/adam/.config/mango/autostart.sh
exec-once=uwsm-app awww-daemon
exec-once=uwsm-app waybar
exec-once=uwsm-app wl-clip-persist --clipboard regular
exec-once=uwsm-app wl-paste --type image --watch cliphist store
exec-once=uwsm-app wl-paste --type text --watch cliphist store
exec-once=awww img "$(cat ~/.cache/wal/wal)"
