source=./input.conf
source=./bind.conf
source=./monitors.conf
source=./animations.conf
# source=./style.conf

# global
allow_tearing=2
cursor_hide_timeout=5
exchange_cross_monitor=1
focus_cross_monitor=1
focus_cross_tag=1
idleinhibit_ignore_visible=1
syncobj_enable=1
xwayland_persistence=0

# shadows
layer_shadows=1
shadows=1
shadows_blur=30
shadows_size=15

# borders
border_radius=5
borderpx=2
focused_opacity=0.8
unfocused_opacity=0.8

# style
cursor_size=24
cursor_theme=Adwaita

exec-once=~/.config/mango/autostart.sh
